### PR TITLE
Convert ZetkinBlocks to editorJsBlocks to make DeliveryErrors handle properly

### LINKED ISSUE #2263: Email: Sending allowed even with missing button URL
## Description
In production, one email was sent while the buttons had no links. This should not be possible. If a user creates a button but does not add a URL there will be a small yellow warning triangle next to the button in the outline. But there should also be an error message in the "delivery" popper, which I guess in some (or all?) cases doesn't work since someone managed to get past it.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Go to any project (or create a new one)
3. Create a new email
4. Define any target group
5. Lock the targets
6. Go to "Compose"
7. Under "settings", add a subject line
8. Add a button with some text, but do not define a URL
9. Click "Delivery"

### Expected Behaviour
Because the button is not fully defined (it has no URL) delivery should be prevented. There should be an error message in the delivery box saying that the email can't be scheduled or sen yet.

### Actual Behaviour
The normal delivery popper shows up with a scheduling UI. There's nothing preventing the user from sending the email even though the buttons have no URLs.

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by a-jaxell**
## Description

When investigating #2263 I found that content blocks in `deliveryProblems.ts` was passed to 
`blockProblems.ts` without being converted to match the proper data type used.

This resulted in `blockProblems()` returning an empty array because it could not find any `type` properties when 
`kind` properties were actually present.

## Screenshots

https://github.com/user-attachments/assets/1a0c1c18-3180-4fac-b111-857a46f2955b

## Changes

* Adds a conversion of blocks in `deliveryProblems.ts`

## Notes to reviewer
**Set as draft until tests are passing locally** 

My tests are failing locally atm, and I am not sure why at the moment. 
When logging output in the test `blockProblems()` returns an empty array.

1. Go to http://localhost:3000/organize/1/projects/35/emails
2. Create edit any email
3. Add a button
4. Click Delivery - Content Error should be displayed
5. Fill in text and link on button
6. Click Delivery - Content Error should not be displayed

## Related issues
Resolves #2263

### CODE REVIEW

**Comment by richardolsson** [comment]
Well spotted @a-jaxell! As you've seen, the tests are failing. In the future, I would recommend using TDD for issues like these, where there are simple tests.

When you find a bug like this, you would first create a test that reproduces it, and then write a fix for that test. In most cases, arriving at a functional fix will be faster, and once you consider that by the time you're done you already have a test written, the time saved will be even bigger.

**Comment by a-jaxell** [comment]
Thanks for the input, I'll give it a go as soon as I'm able. 🙂

**Review by richardolsson — APPROVED** [review]
I'm happy with this! 

(But I can't wait until we get to throw out this editor and replace it with some fresh, homemade code) 🍞

**Comment by a-jaxell** [comment]
A bit late to the party but well done! :)

**Pull request merged**
