### PR TITLE
Issue 1779/personnummer validation

### LINKED ISSUE #1779: Importer: Swedish "personnummer" is not translated as date
## Description
When importing people, if the organization for example uses swedish "personnummer" as a person's date-of-birth, it is not possible to import this as a date as the importer as it only wants dates that are of a specific shape. 

## Steps to reproduce
1. Start an import by going to `orgs/1/people` and selecting "import people" from the top right corner menu
2. Select a file that has a column containing swedish "personnummer"
3. Select to import this column as "Extra date"
4. Also select an ID so that you can click "Validate" at the bottom right corner

### Expected Behaviour
Recieve no errors

### Actual Behaviour
You get an error message that the values are of the wrong format and cannot be imported as dates.

## Screenshots (if you have any)
bild

## Suggested solution
Use similar logic as in "gen 2" to do a special solution for the swedes.

### PR DESCRIPTION
**Pull request by alexandrakoch**
## Description
This PR adds personnummer validation to `predictProblems.ts`, using the `verifiera` library.

## Changes

* Adds `verifiera`dependency
* Changes `predictProblems.ts` to accept Swedish format 'personnummer'

## Related issues
Resolves #1779

### CODE REVIEW

**Comment by alexandrakoch** [comment]
The current code throws an error when importing to the DB, it could be that it needs to be in date format? The library I'm using has functions for getting dates from the personnummer, but it's not code I'm familiar with so if someone wants to do those changes or help guide me, feel free!

**Comment by alexandrakoch** [comment]
This is my test data:

[Exempeldata Zetkin.csv](https://github.com/zetkin/app.zetkin.org/files/14469007/Exempeldata.Zetkin.csv)

**Comment by ziggabyte** [comment]
Long time since this was started on but I'm gonna take a look and see if I can work something out!

**Comment by richardolsson** [comment]
This PR is superseded by #1981, in which we chose a slightly different route, creating a more generalized way of parsing dates during an import.

**Pull request closed without merging**
