### PR TITLE
Alert Styles

### LINKED ISSUE #381: Alert style
The aim is to make the `alert` stand out against the grey background color. See #344 

scc

### PR DESCRIPTION
**Pull request by niklasva82**
Resolves #381

Supersedes #405 (due to rebase)

### CODE REVIEW

**Comment by richardolsson** [comment]
This PR does not pass CI. Please review and fix errors before peer review.

**Comment by djbusstop** [comment]
## Newly created task
NewAlert

## Editable Task
EditableAlert

## Task that's being assigned
AssignedAlert

## Task that's been published and assigned
PublishedAlert

**Comment by djbusstop** [comment]
## Newly created task
NewAlert

## Editable Task
EditableAlert

## Task that's being assigned
AssignedAlert

## Task that's been published and assigned
PublishedAlert

**Review by richardolsson — APPROVED** [review]
We need to eventually settle on the color scheme here, and I'm not a big fan of how the colors go together now. The issue is that there is no overarching theme or identity on which all colors are based.

But as far as code design goes this PR is a big improvement so I say let's merge it now and we can revisit theming later in a more focused manner.

Do ou want to merge @djbusstop?

**Comment by richardolsson** [comment]
> Do you want to merge @djbusstop?

Or should @niklasva82?

**Pull request merged**
