### PR TITLE
ignore breadcrumbs to surveys and callassignments

### LINKED ISSUE #1749: Some breadcrumbs lead astray
## Description
The breadcrumbs for "Call assignments" and "Surveys" lead to weird places. They should be removed entirely.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects
2. Click on Activities
3. Click on any survey or call assignment
4. In the breadcrumbs, click "Surveys" or "Call assignments"

### Expected Behaviour
Should lead to someplace useful.

### Actual Behaviour
Leads to a 404, because there is no page at the paths that represent those breadcrumbs.

## Proposed solution
Change the breadcrumbs backend code to ignore these paths, similar to how it's been solved for lists.

### PR DESCRIPTION
**Pull request by annafock**
## Description
removes breadcrumb items that are not leading to an existing page

## Screenshots
[Add screenshots here]

## Changes
[Add a list of features added/changed, bugs fixed etc]

* Adds…
* Changes…

## Notes to reviewer
[Add instructions for testing]

## Related issues
Resolves #1749

### CODE REVIEW

**Comment by richardolsson** [comment]
Removing "Surveys" and "Call assignments" was the solution that me and @annafock agreed on. I actually think that's nice. What do you think @ziggabyte (disregarding the issue)?

That the project is missing seems like a mistake though. Could it be because it's "standalone" in this case, and "standalone" is removed from the breadcrumbs? Maybe that's creating a situation that I didn't foresee when we agreed to just remove "Surveys" and "Call assignments".

**Comment by ziggabyte** [comment]
@richardolsson I think this solution works, given that you get the link to the project you are in (if there is one). The screenshots I have in my comment are not from standalone activities, but belong to a project (id 127)...

**Comment by ziggabyte** [comment]
@annafock Now that I better understand the thinking, I don't think it is a problem, but that potential bug that is unrelated to what you have done i will note down and it can be worked on separately. So I'm gonna give a review now!

**Review by ziggabyte — APPROVED** [review]
I apologise for the delay on this review! I have made a separate issue for the behaviour that is on `main` and not a result of your work, where the project title is missing from the breadcrumbs. 

I believe this is good and does not require changes!

**Pull request merged**
