### PR TITLE
Add ReduxProvider to storybook and remove react-query

### PR DESCRIPTION
**Pull request by henrycatalinismith**
Fixes https://github.com/zetkin/app.zetkin.org/issues/1761.

| Before | After |
|-|-|
| Screenshot 2024-02-03 at 10 49 07 | Screenshot 2024-02-03 at 10 56 08 |
| Screenshot 2024-02-03 at 10 49 33 | |

### CODE REVIEW

**Comment by richardolsson** [comment]
I think is similar to something that @ziggabyte already did in another branch (probably the email feature?), but I see no reason not to merge this already, and then just deal with the conflict (if there even is one) once we merge email.

What do you say @ziggabyte?

**Comment by ziggabyte** [comment]
> I think is similar to something that @ziggabyte already did in another branch (probably the email feature?), but I see no reason not to merge this already, and then just deal with the conflict (if there even is one) once we merge email.
> 
> What do you say @ziggabyte?

I agree! If there even is a merge conflict it will be minor :D Let's go!!

**Review by ziggabyte — APPROVED** [review]
Let'ss goooooo

**Comment by henrycatalinismith** [comment]
Means a lot! First code contribution to actually make it into `main`!!

**Pull request merged**
