### PR TITLE
Allow max client body size of 50 mb for bulk operations

### PR DESCRIPTION
**Pull request by niklasva82**
## Description
This PR allows a body size of up to 50 MB for bulk operations.

### CODE REVIEW

**Comment by richardolsson** [comment]
Nice! Can you make it work for file uploads as well?

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! I have reviewed the nginx configuration and I have tried uploading (to the preview step) a bulk procedure configured from a large CSV file in the importer.

Unfortunately, I still get 413 when the JSON payload is 5388899b (roughly 5 MB). Have you tried this locally and found it to be working @niklasva82? Judging from the response headers, I'm thinking maybe this is Vercel that is stopping the request (which would only be a problem on the dev server.

image

**Comment by richardolsson** [comment]
I just realized the nginx config is only used in production, so the only way to test this truly is to deploy to production. One could also, of course, run the app locally using the docker setup. Have you done that @niklasva82?

**Comment by niklasva82** [comment]
Yes that is a problem, I tried booting the container only to verify that the config is working, but I can't seem to get the container working properly locally regardless of the config, this seems to require some more docker voodoo which I haven't invested time in. But this is how it was solved on the api for the old imports as well as files, so this should work.

**Comment by richardolsson** [comment]
> Yes that is a problem, I tried booting the container only to verify that the config is working, but I can't seem to get the container working properly locally regardless of the config, this seems to require some more docker voodoo which I haven't invested time in. But this is how it was solved on the api for the old imports as well as files, so this should work.

Fair enough! Let's get this merged and try it in production. 😊

**Review by richardolsson — APPROVED** [review]

**Pull request merged**
