### PR TITLE
Issue 2013/can import organizations from multiple columns

### LINKED ISSUE #2013: Imports: Can only import organizations from one column
## Description
It's currently only possible to import organizations from a single column, even though there is nothing technically preventing the case of a single file having multiple columns that represent organization membership.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Click on "Create…"
3. Click on "Import people"
4. Drop any CSV file (e.g. example below) with at least 2 columns
5. For the first column, pick "Organizations" as the target
6. For the second column, pick "Organizations" again

### Example CSV
```csv
ID,FIRST NAME,LAST NAME,CHAPTER,NETWORK
1,Clara,Zetkin,Leipzig,Feminist network
```

### Expected Behaviour
Picking organizations again should be allowed, and mapping values to organizations in both columns should result in organizations from both columns to be included when producing the final output (while avoiding duplicates).

### Actual Behaviour
It's not possible to pick "Organizations" again in step 6, because it will have been disabled.

## Screenshots (if you have any)
image

## Proposed solution
This will probably affect several parts of the import system:

* The `optionAlreadySelected()` function in `useColumn()` will need to be updated
* The `prepareImportOperations()` function may need to be updated in order to support collecting organization IDs from several columns
* The `usePersonPreview()` function may need to update in order to collect organizations from multiple columns

### PR DESCRIPTION
**Pull request by katjam**
## Description
This PR allows import data for people to contain multiple columns mapped to organization

## Screenshots
image
image
image

## Changes
* Previously an import csv could only contain one organization type column per row
* Now each row can contain mapping to multiple organizations for each individual

## Notes to reviewer
* Use the Create -> Import people function on `/organize/[orgId]/people` to upload a csv containing multiple columns containing organization name
* Validate & verify that the validation and previews correlate with expectations
* Import & verify that people are added to multiple organizations as per csv data

## Related issues
Resolves #2013

### CODE REVIEW

**Comment by katjam** [comment]
@richardolsson I fixed that `check-types` error yesterday - so should be good to relaunch the workflow & review.

**Review by richardolsson — COMMENTED** [review]
I'm sorry for the delay in getting back to you on this. I've tried the preview build and looked at the code and it looks very good to me. It's amazing work! 

Some of it is quite complex, so ideally I would like some tests to be added for `createPreviewData` and `prepareImportOperations` (both of which have tests for other parts of their functionality).

Do you think that's something that you'd be able to do?

**Comment by katjam** [comment]
> I'm sorry for the delay in getting back to you on this. I've tried the preview build and looked at the code and it looks very good to me. It's amazing work!
> 
> Some of it is quite complex, so ideally I would like some tests to be added for `createPreviewData` and `prepareImportOperations` (both of which have tests for other parts of their functionality).
> 
> Do you think that's something that you'd be able to do?

Yes, very sensible idea. I'll try to get some tests up this weekend... or next week.

**Comment by katjam** [comment]
@richardolsson Tests added.

**Review by richardolsson — APPROVED** [review]
Great work on the tests @katjam! I have reviewed the code and tried the preview build again, and everything looks great. I think this is ready to be merged. It just missed a release, but will be in the next one. 💯

**Pull request merged**
