### PR TITLE
More style rules

### PR DESCRIPTION
**Pull request by richardolsson**
This PR adds a few more code style rules to `.eslintrc`:

* Prohibit use of `switch` entirely. There are few cases (if any) where they're better than `if`/`else`
* Require newline after closing `}`
* Require empty lines after blocks of imports, and around individual functions and exports
* Require imports, keys and vars to be sorted

### CODE REVIEW

**Comment by richardolsson** [comment]
I'm especially curious about your reaction to enforcing newlines after closing `}`, @niklasva82, because I know we have different preferences about this. The rule means that `if-else` must be written like this:

```js
if (isTrue) {
  // Do something
}
else {
  // Do something else
}
```

It prohibits the following style:

```js
if (isTrue) {
  // Do something
} else {
  // Do something else
}
```

I think we should be consistent about this, but I'm open to changing my mind about the preference, if you can motivate why we should use the other one. :)

**Comment by niklasva82** [comment]
As long as it's codified and can be fixed automatically I'm fine with any style :)

**Comment by niklasva82** [comment]
Regarding imports however I like to separate library imports from local imports, is this possible to codify in eslint so that it doesn't sort only by alphabet?

**Comment by richardolsson** [comment]
> Regarding imports however I like to separate library imports from local imports, is this possible to codify in eslint so that it doesn't sort only by alphabet?

I completely agree! I have added configuration to support this now. The `allowSeparatedGroups` property is of course more generalized than separating local/external imports (it will allow any type of separation) but I think that's fine.

**Pull request merged**
