### PR TITLE
Move contributing instructions to separate file and improve them

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR creates a new `CONTRIBUTING.md` document, moves some developer instructions from the README to the new file, and improves it to be more comprehensive. It also moves information about testing to a new `TESTING.md`, in order to keep the `README.md` short and focused on running the project.

## Screenshots
None

## Changes
* Moves testing instructions from `README.md` to `TESTING.md`
* Moves contributor instructions from `README.md` to `CONTRIBUTING.md`
* Develops the contributor instructions with some additional information

## Notes to reviewer
Please let me know what you think about these instructions, especially if you're a newcomer!

## Related issues
Undocumented

### CODE REVIEW

**Comment by richardolsson** [comment]
I think the playwright tests are failing because of issues with the dev server. I'm fixing it!

**Comment by richardolsson** [comment]
I guess I was right about the playwright tests, which are now passing. 😊

**Review by amerharb — APPROVED** [review]

**Review by ziggabyte — APPROVED** [review]
Love it! Clear and informational :D

**Comment by richardolsson** [comment]
Thank you @amerharb and @ziggabyte for reviewing! Your approval and the feedback I've received elsewhere makes me comfortable merging this. 😊

**Pull request merged**
