### PR TITLE
Fix problem with email inline link editor disappearing

### LINKED ISSUE #2176: Links (inline tool) in email composer behaves erratically
## Description
Our email composer uses the [Editor.js library](https://editorjs.io/) but we have implemented our own link inline block because we felt the included one had a lot of issues. During development, I remember everything working very well, but around the time of release I started noticing this weird behavior. Creating a link works well, but after selecting an existing link the inline tool doesn't work as expected. It doesn't indicate that a link is selected, and there seems to be no way to edit the URL of a link.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Go into any project or create a new one
3. Create a new email
4. Go to the Compose tab
5. Write some text, e.g. "This is a paragraph and it will contain a link somewhere in the middle."
6. Select some text in the middle of that sentence, e.g. "a link"
7. Click the link button and type a URL
8. Select all or part of the linked text

### Expected Behaviour
The toolbar that appears should highlight the link icon and display the input field where I can edit the URL. At this point, clicking the now different link button should _remove_ the link.

### Actual Behaviour
The toolbar appears unchanged, and there is no input field to update the URL, but clicking the link button does remove the link.

### Creating a link (works well)
image

### Selecting an existing link
I would expect to see the link button highlighted (compare with selecting a piece of bold text) and that the input field where I can add the URL to be visible.

image

### PR DESCRIPTION
**Pull request by awarn**
## Description
Our own event listening for changes to selection (and then updating tool state) triggered too early. Editor.js runs through closing and opening the toolbar every time the selection changes, with a call to checkState function meant to decide if we should open it (again).

Previously we would run our own update, where the logic for deciding to have toolbar open was, which displayed it. Then Editor.js would close it and call checkState, but because there was no code there for keeping it open, it would remain close. So the link tool would just briefly flash open.

## Changes
* Email inline link editor now visible when selecting text after link creation.
* Change inline variable editor to also use correct lifecycle.

## Related issues
Resolves #2176

### CODE REVIEW

**Review by richardolsson — CHANGES_REQUESTED** [review]
Very impressive how you were able to figure this one out. But now typescript is complaining. Can you have a look?

**Comment by awarn** [comment]
Not a _great_ fix, even if it worked. checkState() does not have any reference to a return type (other than void), but the type requires boolean. I have tried returning both true and false, and there is no difference in behavior what I can tell.

**Comment by richardolsson** [comment]
> Not a _great_ fix, even if it worked. [Docs for checkState()](https://editorjs.io/inline-tools-api-1/#checkstate) do not have any reference to a return type (other than void), but the type requires boolean. I have tried returning both true and false, and there is no difference in behavior what I can tell.

Good enough! We are hoping to replace Editor.js soonish (because we've been having a lot of problems with it) so less-than-perfect solutions are more than good enough at this point. 😊

**Review by richardolsson — APPROVED** [review]
Nice work figuring this out! I'm not sure why it was so complex before, if it could be so much simpler.

I know we struggled with it a lot, to get it to work in both Chrome and Firefox, which this PR also does. I can see that this solution is not working in Safari, but neither was `main`, so that's not the reason for the added complexity.

Seeing as how this seems to be working better then `main`, I'm going to go ahead and merge. I can't wait to replace this Editor.js and all of it's weirdness with something else soon. 😊

**Pull request merged**
