### PR TITLE
OOP call assignment targeting

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR is a feature branch for all the work done in multiple other PRs.

## Screenshots
None

## Changes
* Adds redux store
* Adds `CallAssignmentModel` on top of store
* Implements the overview page

## Notes to reviewer
None

## Related issues
See individual PRs:

* #826
* #843
* #845 
* #846
* #848

### CODE REVIEW

**Comment by richardolsson** [comment]
I'd like to merge this into `main` next, but there are some minor CI issues with some of the code you wrote @ziggabyte. Can you take a look at it?

**Comment by ziggabyte** [comment]
> I'd like to merge this into `main` next, but there are some minor CI issues with some of the code you wrote @ziggabyte. Can you take a look at it?

**Comment by ziggabyte** [comment]
sorry for close and reopen i just accindently clicked the button

**Review by ziggabyte — APPROVED** [review]
this is fucking awesome

**Pull request merged**
