### PR TITLE
Survey response cell (and misc related changes)

### LINKED ISSUE #898: View cell for Survey Response column
## Description
The cells in a Survey Response column should show the text response of a survey question (only relevant when the response type of the question is “free text”). 

There may be multiple responses to the same question from a single person, in case they submitted the survey more than once. 

## Relevant Job Stories
(no specific ones)

## Requirements
- [x] Shows text if there is a response
- [x] Shows nothing if there is no response
- [x] Truncates response text if it is too long.
- [ ] Clicking the cell should open full survey submission (responses to all questions).
- [x] When hovering cell with response, it shows "popper" with full text response and references to previous responses to the same survey (if there are any)
- [x] In the popper it shows relative time to how long ago each response was submitted.
- [x] Links in popper opens full submission of relevant survey.
- [ ] When filtering or searching and the match is for text in a previous response, the text where the match is is shown and the matching string is in bold.

## Design specifications
https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=1976%3A36118&t=ZwOBKqXDfw3cdL7Y-4
bild

### LINKED ISSUE #906: Survey submission drawer
## Description
A user should be able to read the responses in a survey submission without leaving a view.

## Relevant Job Stories
* When I’m using sheets to research survey responses, I want to be able to open the survey submission in context, so that I can look at it while I continue to work the sheet

## Prerequisites
None required, but might make sense to wait until #898 and #903 are done.

## Requirements
- [x] When clicking a survey submission link in a view, open a side panel "drawer"
- [x] The panel should slide in from the right hand side
- [x] The panel should have a close button to remove it again
- [x] The panel should render the full survey submission (see design specification)

## Possible implementations
Load the full submission from `/orgs/ID/survey_submissions/ID`.

## Design specifications
image

## Open questions
* How do we avoid hiding content behind the panel? Maybe add padding to the view?
* How does the panel scroll?

### LINKED ISSUE #912: View cell additional survey submission info
## Description
Users need to see more information about someone's survey submissions. 
In three types of view cells, #903 #907  and #908 , there is need for this popper type component that displays additional information about survey submissions. 

## Relevant Job Stories
(no specific for this one, see aforementioned issues for details)

## Requirements
- [x] Shows most recent submission
- [x] Shows previous submissions
- [ ] Survey Response: Highlights text in previous survey response if that text matches search or filter, and not most recent response
- [ ] Survey Option: Shows which previous submission had this option, if filtering/searching and it's not the most recent submission that matches

## Design specifications
Figma: https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=2358%3A47067&t=ZwOBKqXDfw3cdL7Y-4

Design from Survey Options 
bild
Design from Survey Option
bild
Design from Survey Response
bild

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR adds support for the first new cell design (survey response) and in doing so introduces a number of new features and frameworks.

## Screenshots
image

## Changes
* Adds new `SurveySubmissionPreview` component, as described in #912
* Revamps the framework for how to render view cells using `IColumnType` classes
* Adds `SurveyResponseColumnType` to render survey response cells in browser and downloads
* Adds framework for opening side panes using context and the new hook `usePanes()`
* Adds a new `surveys` feature with:
  * Store logic and actions for loading surveys and submissions
  * Repo for loading surveys and submissions
  * `SurveySubmissionModel` to assemble a "hydrated" submission, object which contains both responses and the text of the original questions
* Adds new `LoadingFuture` shorthand class
* Adds better support for large timespans (e.g. years) in `ZUIRelativeTime`
* Fixes bug in `ZUIRelativeTime` preventing the tooltip from rendering correctly
* Fixes z-index issue with `ZUIPersonHoverCard`

## Notes to reviewer
This PR implements most of the things described in three separate issues, but not all of it. The remainder is left for a future issue, because it's not high enough priority for this cycle.

Please let me know if something is missing that you think should be there.

Also, note that the submit date is not included as expected in all cell types in the current API. This is being worked on and will be included in a future update to the API. This code expects it to be there, which it will before release.

## Related issues
Resolves #898 
Resolves #906 
Resolves #912

### CODE REVIEW

**Comment by ziggabyte** [comment]
> Also, note that the submit date is not included as expected in all cell types in the current API. This is being worked on and will be included in a future update to the API. This code expects it to be there, which it will before release.

is this what the comment above refers to, that it says "now" at most recent, even though response was posted 238 days ago?
bild

**Review by ziggabyte — COMMENTED** [review]
Really nice, just had two small comments! So good to have a framework to just churn out column types for a few days now :)

**Comment by richardolsson** [comment]
The invalid date is due to changes that are still pending on the server, but will work when the new version is deployed.

The error is not really related to this PR, but will be easier to fix in the next PR I'm working on, so I think we should move on and hold off on fixing it until then.

I've renamed the misspelled type, and I have added more padding, also moving it to the scrolling container so that the scrollbar appears at the outer edge of the pane, not inside the padding.

Ready for re-review! 😊

**Review by ziggabyte — APPROVED** [review]
Wohooo let's go!

**Pull request merged**
