### PR TITLE
# Issue 2199: `Tomorrow` should only be the relativeTime label if it's next day, not simply if it's +24 hours in the future

### LINKED ISSUE #2199: Journeys: Time zone issue in journey milestone date.
## Description.
When I set the date of a milestone of a journey, the representation of that date in relative time in the "Next milestone deadline" column in the journeys list is not correct. This (i think) is because that when the milestone date is set, it's set at the time of `00:00:00` on the selected date. So in the journeys list this is the time that comes from the server, and then is converted to local time of the browser (for me currently in Sweden, that means it adds 2 hours). 

## Steps to reproduce
1. Go to a journey
2. Go to the "milestones" tab
3. Set the deadline of a to the date that is two days from the current date
4. Go to the over view of all journeys, `organize/{orgId}/journeys`
5. Look in the "Next milestone deadline" column 

### Expected Behaviour
It correctly says that the next milestone deadline is two days from now

### Actual Behaviour
It says that the next milestone deadline is tomorrow

## Screenshots (if you have any)

In this screenshot, Sept 30 is correct, that is the date that i chose for the milestone - but "tomorrow" is incorrect, as you see the date of the day i did this is Sept 28th. 
bild

### PR DESCRIPTION
**Pull request by troldmand**
## Description
This PR patches the issue where a relativeTime label is `Tomorrow`, when it should be `in 2 days`.  

## Screenshots

If the date is 12th of november, and deadline is 14th of november, then it will show as **tomorrow**:
 Screenshot 2024-11-13 at 06 08 36

The fix will handle that case and instead show **in two days**: 
Screenshot 2024-11-13 at 06 13 28

The issue only appeared if there's less than 24 hours to the deadline. 

## Changes

* Because `nextMilestoneDeadline` is always set to 00:00AM (midnight), this fix will compare and calculate the `const difference` variable from the `00:00` of now's date, instead of the actual current time of now's date. 
* Patch is scoped to only take effect on the case timeline (`/organize/1/journeys/1/1`) and on the journey case tabel (`/organize/1/journeys/1`):
Screenshot 2024-11-13 at 06 55 16
Screenshot 2024-11-13 at 07 01 41

## Related issues
Resolves #2199

### CODE REVIEW

**Comment by richardolsson** [comment]
Why is "in 2 days" better than "tomorrow"?

I'm trying to wrap my head around this, and if I understand correctly, the fundamental problem here is that the UI is trying to render the absolute deadline (in the tooltip) including _time_, even though users cannot set the time, only the _date_.

To me it feels weird to change `ZUIRelativeTime` for this, since this is a special case for this situation. I would either make changes specifically for this table, or I would introduce a new `ZUIRelativeDate` component if that is what we want.

But again, I'm not entirely sure I understand the solution. I might also be misunderstanding the problem, but I don't think the problem here is related to some error in the calculation of the difference, but rather in how the dates are parsed because of timezones.

What are your thoughts reading this?

**Comment by troldmand** [comment]
> Why is "in 2 days" better than "tomorrow"?

Because in this case, it's not tomorrow, it's in two days time. So "the day after tomorrow" would be okay, but "tomorrow" is exactly the 'wrong-case' we are trying to solve.

> I'm trying to wrap my head around this, and if I understand correctly, the fundamental problem here is that the UI is trying to render the absolute deadline (in the tooltip) including _time_, even though users cannot set the time, only the _date_.

Yes! The milestones only have a date, so the timestamp is defaulting to 00:00 AM. Then the table wants to display relative time to the milestone. So it makes sense that a lot of us thinks that this is a timezone issue, but my finding when reproducing, is that it's not a 'off by GMT+2 hours' situation, as @Herover also finds on the issue. 

> To me it feels weird to change `ZUIRelativeTime` for this, since this is a special case for this situation. I would either make changes specifically for this table, or I would introduce a new `ZUIRelativeDate` component if that is what we want.

Agreed, if this patch should be merged, we need it to be scoped only to this table of milestones. 

> But again, I'm not entirely sure I understand the solution. I might also be misunderstanding the problem, but I don't think the problem here is related to some error in the calculation of the difference, but rather in how the dates are parsed because of timezones. 

With a nifty little time-traveler-chrome-extension, I debunked this, it's not a timezone problem, but a problem with how these relativeTime strings are calculated:

Screenshot 2024-10-17 at 13 40 55
https://github.com/zetkin/app.zetkin.org/issues/2199#issuecomment-2381276330

**Comment by troldmand** [comment]
@ziggabyte and @richardolsson, I have updated on this fix and I would like you to reconsider if this is merge-able 🫡 The PR description should be a bit clearer now.

**Comment by ziggabyte** [comment]
@troldmand Realtive time is a troublesome thing and after having some discussions in the team about all the potential edge cases and misunderstandings that can arise from using words like "Tomorrow", we have decided to just remove the relative time from this column and just show the date for the next deadline. 

Thank you for giving your time and energy to this very mind-bending topic ⭐ I hope it does not feel too sour that this becomes the conclusion of your investigations 🔍

**Comment by troldmand** [comment]
> @troldmand Realtive time is a troublesome thing and after having some discussions in the team about all the potential edge cases and misunderstandings that can arise from using words like "Tomorrow", we have decided to just remove the relative time from this column and just show the date for the next deadline. 
> 
> Thank you for giving your time and energy to this very mind-bending topic ⭐ I hope it does not feel too sour that this becomes the conclusion of your investigations 🔍 

I completely understand! Often a shitty solution is needed to make a better decision, so I don't think it was any waste. 🤘

**Pull request closed without merging**
