### PR TITLE
Add loading animation for ActivityListItem

### LINKED ISSUE #1142: Activity list items show zero stats while loading
## Description
While activity stats are loading, I think the item should show some sort of loading indicator instead of showing zeros, as is currently the case.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/6/activities
2. Watch how the activities load (potentially throttle your browser or use redux dev tools to see the different states)

### Expected Behaviour
First the list should appear. While the stats load, the stats should be showing some sort of a loading indicator. After the stats load, the three numbers should appear.

### Actual Behaviour
First the list appears, but with all zeroes for the stats. Then after a short while (when the stats load) the zeroes are updated with the correct numbers.

## Proposed solution
This will require refactoring in some way how the `ActivityListItem` component works, which I think is fine. Maybe add a `statsLoading` property or something?

As a loading indicator, use MUI `<CircularProgress>`

### While loading
I reproduced this state using redux dev tools to disable the `statsLoaded` action.

image

### After loading
image

### PR DESCRIPTION
**Pull request by theo8theo8**
## Description
This PR adds a loading animation using `<CircularProgress>` when loading the activity stats in `ActivityListItem`.

### While loading
image

### After loading
image

## Changes
* Adds a `statsLoading` property for `ActivityListItem`
* Changes the three components using `ActivityListItem` to also send the extracted prop `statsLoading`
* Adds a `CircularProgress` to `ActivityListItem` when stats are loading

## Related issues
Resolves #1142

### CODE REVIEW

**Comment by richardolsson** [comment]
Nice work @theo8theo8! At first glance this looks great. ✨ 

This unfortunately won't make it into our R38 release which is going out tonight, so someone will return to review this properly and merge it later this week.

**Comment by richardolsson** [comment]
By the way, @theo8theo8, I would love to send an invite to our Slack! If you want to join, share your email address here or by sending me an email at richard@zetkin.org, and I will send an invite. 👋

**Comment by theo8theo8** [comment]
> By the way, @theo8theo8, I would love to send an invite to our Slack! If you want to join, share your email address here or by sending me an email at [richard@zetkin.org](mailto:richard@zetkin.org), and I will send an invite. 👋

Oh, for sure. It is meier.strom.theo@gmail.com

**Review by richardolsson — APPROVED** [review]
Awesome work on this! I have no objections. 😊

**Pull request merged**
