### PR TITLE
Moving views and folders

### LINKED ISSUE #902: Move views and folders
## Description
A user should be able to move an existing view or folder into another folder.

## Relevant Job Stories
* When I have multiple sheets that are related, I want to be able to store them together, so that I can easily find one after having found another

## Prerequisites
Don't start until #897 is done.

## Requirements
- [x] Dragging a view or a folder onto another folder should move it into that folder
- [x] Dragging over a folder should highlight it
- [x] Dragging a view or folder onto the "Back to…" option at the top of sub-folders (#897) should move it up one level
- [x] When dragging over the "Back to…" option, the text should change to "Move to…"

## Possible implementations
Try using the builtin "reordering" functionality of MUI X `DataGrid`, but I think it's unlikely that it will work well. If not, try using [`react-dnd`](https://react-dnd.github.io/react-dnd/).

## Design specifications
None

## Open questions
What should the highlight of folders look like when dragging?

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR implements drag-and-drop to move views and folders in the view browser. A small preview is shown while dragging, and the folders underneith react when dragging a view/folder over them.

## Screenshots

https://user-images.githubusercontent.com/550212/213091240-c37e0016-7219-4c95-8522-9de9fb6d539d.mov

## Changes
* Refactors `ViewBrowser` to be a component directory with a number of sub-components
* Adds model, repo and store logic for moving browser items into folders
* Implements `react-dnd` for dragging and dropping
* Tweaks the visuals
  * Folders react by switching icon and going **bold** when dragging something over it
  * Dragging something previews it as a little elevated card with icon and title

## Notes to reviewer
There is a bug in the dev version of the Platform API which means it's not possible to move a view or folder into the root, so if you move something into a folder, you can't move it back out again. A fix is coming.

## Related issues
Resolves #902

### CODE REVIEW

**Comment by richardolsson** [comment]
I couldn't help myself, so I added some light animation to the drag preview. When the user starts dragging, the preview scales up under the cursor, at a slight tilt. When dragging over a folder (where it can be dropped), the preview scales down slightly. The rotation and size of the shadow follows.

I have updated the PR description above with a video of the animation in action.

**Review by ziggabyte — CHANGES_REQUESTED** [review]
I love it, but when I'm playing with it (in Firefox) it's behaving a little bit buggy :( 
Big thing
- When I'm in "all views" i can drag and drop onto a folder, but when I'm in a folder and want to drag and drop it onto "move to all views", it does not move the view. Moving back and forward in folders seems to work ok, but something is up with "move to all views" 
Smaller things, not bugs just my experience in playing with it
- I am also noting a bit of frustration when playing with it as my instinct is to try to drag from anywhere on the row, but I can only drag from the title. 
- Also my instinct wants to click the arrow on the back row to go back, but i have to click the words "back to all views"

**Comment by richardolsson** [comment]
> I love it, but when I'm playing with it (in Firefox) it's behaving a little bit buggy :( 
> 
> Big thing
> - When I'm in "all views" i can drag and drop onto a folder, but when I'm in a folder and want to drag and drop it onto "move to all views", it does not move the view. Moving back and forward in folders seems to work ok, but something is up with "move to all views" 

This is because of the backend bug described in the notes to reviewer above.

> 
> Smaller things, not bugs just my experience in playing with it
> - I am also noting a bit of frustration when playing with it as my instinct is to try to drag from anywhere on the row, but I can only drag from the title. 
> - Also my instinct wants to click the arrow on the back row to go back, but i have to click the words "back to all views"
> 

Do you think this needs to be fixed? I can if you want!

**Comment by ziggabyte** [comment]
> This is because of the backend bug described in the notes to reviewer above.
duuuuuh ok thank you for pointing that out, I clearly mixed up this :D 

> 
> Do you think this needs to be fixed? I can if you want!
The arrow I feel most strongly about, the other I think can rest and we see how it evolves and how we/others feel about it

**Comment by richardolsson** [comment]
I have now made the following changes:

* Clicking the back icon goes back
* Clicking a folder or view icon opens the folder or view
* Clicking and dragging an icon correctly drags the item to be moved

Dragging the owner column does not work, but I think dragging the title or folder is probably enough for now?

**Review by ziggabyte — APPROVED** [review]
We love an animated dragon drop!

**Pull request merged**
