### PR TITLE
change messages in button menu

### LINKED ISSUE #2241: Activity creation flow has redundant UI text
## Description
The button to create activities is overtly expressive. 

## Steps to reproduce
1. Go to a project
2. Click on [Create activity] button.

### Expected Behaviour
For the button and menu text to form a cohesive verb + noun combination. 
For instance
1. Call the button "Create" or (even "New").
2. Remove "Create…" from every menu item.

### Actual Behaviour
Says "Create" a whole lot. Makes the start of activity item read exactly the same.

## Screenshots (if you have any)
image

### PR DESCRIPTION
**Pull request by helihard**
## Description
This PR shortens overtly expressive messages relating to the Create Activity button.

## Changes
Changes the text of the Create Activity button to "Create"
Changes the "Create" menu item messages from "Create [activity]" to "[activity]"

## Related issues
Resolves #2241

### CODE REVIEW

**Comment by richardolsson** [comment]
Nice work! Would love to merge, but there's a conflict. Are you able to resolve it (or optionally, pull the latest main and reapply your work in a new branch and a new PR)?

**Comment by helihard** [comment]
Damn am I rusty … Will fix conflict.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work sorting the merge conflict!

I've tried the preview build, and I'm afraid it's not working. The old strings are still being rendered in the UI. This is probably because the `en.yml` file contains the old translations.

This highlights a problem with changing the default text for a message (in `messageIds.ts`) that I didn't think about when I first saw the PR. If we just update the default text, translators will not know that they need to update the localized strings.

The best thing to do would be to move the messages to get another name. Which makes sense for another reason as well. It's kind of weird that these messages are in some arbitrarily named `linkGroup` scope, alongside `public` and `settings` which are not part of the same drop-down.

Maybe they can be added to a separate group called something like `createButton` next to `linkGroup` (but beware of alphabetical order)?

**Comment by helihard** [comment]
Sure!

**Review by richardolsson — APPROVED** [review]
Nice work getting to the bottom of this! 💯

**Comment by richardolsson** [comment]
I squashed and merged, so that all of the commits in this PR are "compacted" into a single commit in `main`: 7d03e1861464489b3dd620faeda0fa368b6631f1

**Pull request merged**
