### PR TITLE
Issue 1002/move popover above assignee

### LINKED ISSUE #1002: Move Popover component above the Person assignee cell in Views
## Description
The Popper component needs to render align and on top of the Person assignee cell. That will be relevant for Views and Surveys.

## Relevant Job Stories
None

## Prerequisites
None

## Requirements
- [ ] Make popover component render on top of cell 
- [ ] Make popover render on click instead on hover

## Possible implementations
None 

## Design specifications
None

## Open questions
None

### PR DESCRIPTION
**Pull request by rebecarubio**
## Description
This PR transform the assignee popover to be placed above or below the cell, making the main input to search the cell itself. 

## Screenshots
Popover below cell, showing assignee
<image src="https://user-images.githubusercontent.com/36491300/219381872-8428516b-5d18-4f85-b91e-1a17483df844.png"  width=200>

Popover below the cell, searching mode
<image src="https://user-images.githubusercontent.com/36491300/219382084-919842a9-96dd-4a55-849c-4a66269c59ae.png" width=200>

Popover above the cell, no assignee
<image src="https://user-images.githubusercontent.com/36491300/219382390-020dc844-3fae-4a21-af10-6613c383c717.png" width=200>

## Changes
* Adds `ReadCell `component to display assignee in a read only state
* Adds `initialValue `property in PersonSelect component 
* Adds `initialValue `of assignee in the cell in edit mode
* Moves Assignee box at the beginning of the Popover element
* Remove Assignee box when cell is in searching mode
* Add comment to disable autoFocus lint rule
* Polishes styles

## Notes to reviewer
Autofocus is set when cell is in edit mode (hard to see it in the screenshots), but I needed to add a comment exception to ignore the lint rule. I´ll be happy to do changes and use `ref `and ` .focus()` but so far couldn't  make it work with the input component.

## Related issues
Resolves #1002

### CODE REVIEW

**Comment by kaulfield23** [comment]
Looks so nice! though I can't get 100% it, I tried to leave a review!

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice! It came out very simple in the end. My only complaint is that the assigned person is no longer centered vertically, like it used to be. Any chance that can be fixed before we merge?

image

**Comment by rebecarubio** [comment]
> Nice! It came out very simple in the end. My only complaint is that the assigned person is no longer centered vertically, like it used to be. Any chance that can be fixed before we merge?

@richardolsson sure!!! I´ll fix it! You´re right it will look nicer centered

**Comment by rebecarubio** [comment]
Requested changes:

centered

centered2

**Review by richardolsson — APPROVED** [review]
I think it looks beautiful now! This was a struggle, but great work! 💯

**Pull request merged**
