### PR TITLE
Add text 'beta' next to Zetkin logo

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR adds text 'Beta' next to Zetkin logo

## Screenshots
image

## Changes

* Adds text 'beta' in logo

## Notes to reviewer
I personally like top-left. But there are options here! Let me know what you think!

image
(red color - theme.palette.primary.main)

image

image

image
font-weight :800 and bigger font size

I didn't add 'beta' text in messageIds. Thought that text 'beta' will be removed at some point. Let me know if i need to add it to messageIds!

## Related issues
Resolves part of #1067

### CODE REVIEW

**Comment by richardolsson** [comment]
Thanks for all the options! What do you think, @Bagera? How would you solve this?

**Comment by Bagera** [comment]
@kaulfield23 and I made some changes together and the badge look like this now
image

**Comment by kaulfield23** [comment]
I like it! It is cute :relaxed:

**Review by ziggabyte — APPROVED** [review]
Looking great! 🅱️

**Pull request merged**
