### PR TITLE
Fix non-dashed empty results after empty segment in makeSankeySegments

### LINKED ISSUE #1579: Sankey diagram renders empty result incorrectly
## Description
When the first filter of a Smart Search query returns no matches, the sankey diagram still renders a filled segment, when it should be a "pseudo" segment.

## Steps to reproduce
1. Go to localhost:3000/organize/1/people
2. Create a new list
3. Configure the list using Smart Search
4. Add a filter that returns no one (e.g. "random" filter with zero as the config, or call filter with dates in the future)
5. Add another filter that returns people (e.g. "random" filter with non-zero config)

### Expected Behaviour
The first segment of the sankey diagram should render a "pseudo" segment, with dashed lines. The next segment should pick up from the pseudo segment and add a "filled" flow from the left.

### Actual Behaviour
The first segment of the sankey diagram renders a regular segment, but with zero-width output. The next segment starts filled from the previous one, but with minimum width resulting in a weird joint between them. 

## Screenshots
image

### PR DESCRIPTION
**Pull request by Herover**
## Description
This PR fixes #1579 by making sure that if the first non-empty add use stroke instead of fill.

## Screenshots
image

## Notes to reviewer
See issue for reproduction steps and how it rendered previously.

We did not attempt to fix the weird join between a 0 add and the next segment.

## Related issues
Resolves #1579

### CODE REVIEW

**Comment by ziggabyte** [comment]
Nice work! I'm wondering if there is a particular reason you decided not to do a test, as suggested in the comment on the issue? 

> To solve this, look at the data returned by the `stats` endpoint, on which the diagram is based. Then take that data and use for a new test for `makeSankeySegments()` and work until the tests pass.

https://github.com/zetkin/app.zetkin.org/issues/1579#issuecomment-1794202517

**Comment by richardolsson** [comment]
Awesome work on this @Herover. If you want to collaborate on a test I'd be happy to help. I don't know if you're experienced with test-driven development, but I love it and would really enjoy getting to share my process for how I would solve an issue like this using TDD (especially now that you've already taken care of the hard part which is finding the actual solution. 😊)

**Comment by Herover** [comment]
Hi, added a test now :)
I haven't made a "opposite" test case since it would be identical to the `'treats non-all as empty start'`-case.

**Review by richardolsson — APPROVED** [review]
Nice work figuring this out! Just this tiny change with the dashed lines makes this so much more clear. I do think it could be improved further and if you're keen on working more on these diagrams we can discuss it (because I think it might be difficult or at least very cumbersome to explain). But this for sure is an improvement and can go into the code as is.

**Pull request merged**
