### PR TITLE
do not include filter again in API call

### LINKED ISSUE #2226: API Proxy: Query strings are included twice in API calls
## Description
The backend code in this web app includes an API proxy, which accepts requests at routes under the /api prefix, and proxies those requests to the Zetkin API. We do this for a number of reasons, but a problem has been that query strings are not properly handled. At first the query string was dropped from the forwarded request, but at some point (60bf5112e5ccd43189f51e340e2910adad872620 ?) that was fixed. Now it seems that the query string is actually included twice, possibly due to changes in how NEXT.js handles query strings?

## Steps to reproduce
This is easiest to reproduce and verify if you're running the Zetkin backend (or anything that accepts and logs HTTP requests) locally.

1. Point api.dev.zetkin.org to 127.0.0.1 in your hosts file or reconfigure the webapp using the `ZETKIN_API_HOST` environment variable to use `localhost`. **NOTE**: make sure to undo this step after fixing the bug
2. Start a local web server, e.g. the full Zetkin backend system or just a simple Python3 http server using `python3 http.server 80` in your terminal
3. Browse to http://localhost:3000/api/orgs/1/people/duplicates?filter=status%3d%3dpending (which is the API request to retrieve potential duplicates, and filtering using a query string to only include pending)
4. Look at the request in the terminal log

### Expected Behaviour
The backend should have received a request to that exact URL.

### Actual Behaviour
The backend seems to get a request to a URL that includes the query string twice:

```
"GET /v1/orgs/1/people/duplicates?filter=status%3d%3dpending?filter=status%3D%3Dpending HTTP/1.1" 404 -
```

Note that this does not seem to happen for all URLs with query strings.

## Screenshots (if you have any)
Here I try three separate requests to our API proxy in the NEXT.js webapp, and in the rearmost terminal we can see how they are made to the backend.

image

### PR DESCRIPTION
**Pull request by remipou**
## Description
This PR prevents adding filter 2 times to the the query string.

## Changes
Removes the whole query string if it contains a `filter` key. Filters are validated and added in another part of the code (see the definition of the `get` method of the ZetkinZResource:
```
  GET: (resource: ZetkinZResource, req: NextApiRequest) => {
    const filters = getFilters(req);
    return resource.get(null, null, filters);
  },
```
and the `getFilters` utility).
A drawback would be if the incoming request had both `filter` and another query parameter, but, by looking at the code, this should not happen. I'll let the reviewer be the judge of that.

## Notes to reviewer
see #2226 

## Related issues
Resolves #2226

### CODE REVIEW

**Comment by ziggabyte** [comment]
King Rémi does it again! (just wanted to pop in with some excitement, might review later!) :D

**Comment by richardolsson** [comment]
Wow that's so quick! I just reported this yesterday. 🚀 

I just want to quickly address this:

> A drawback would be if the incoming request had both filter and another query parameter, but, by looking at the code, this should not happen. I'll let the reviewer be the judge of that.

I do think that this is a problem, actually. The bug that this PR fixes doesn't have any practical effects for the user (or developer). It's just a defect that is kind of weird, and should be fixed.

But the effect of removing non-filter query variables _will_ have effects. Even if it doesn't right now (provided that your analysis of the code is correct, which it may well be) it is likely to in the future. When that happens, finding out the reason will be super difficult because the query variable (e.g. `recursive`) will just be swallowed by the API proxy.

Maybe it's a better option to do the opposite, i.e. stop treating filters differently and treat all query string variables the same?

**Comment by remipou** [comment]
I agree with you, and I think there are 2 ways to adress this:
1. would be to stop treating filters differently but we would loose the validation (invalid operator or missing parameter)
2. would be to add again the eventual second parameter beside the filter, it's just need a bit of refactoring.

I will go with option 2 if you think it's acceptable.

**Comment by remipou** [comment]
Actually I would have like to go with option 2 above but I'm afraid it would need some refactoring in the Zetkin.js package (https://github.com/zetkin/zetkin.js/blob/master/index.js) as the second `?` below is added there.
(`GET /v1/orgs/1/people/duplicates?param1=test&param2=test?filter=status%3D%3Dpending`)

**Comment by richardolsson** [comment]
> Actually I would have like to go with option 2 above but I'm afraid it would need some refactoring in the Zetkin.js package (https://github.com/zetkin/zetkin.js/blob/master/index.js) as the second `?` below is added there. (`GET /v1/orgs/1/people/duplicates?param1=test&param2=test?filter=status%3D%3Dpending`)

I don't think that should be necessary. I know that's where the `?` (as in the literal string) is added, but it's added because the API proxy passes a list of filters, like so:

https://github.com/zetkin/app.zetkin.org/blob/6fe1dc21058bd869295141e28c817342c44e3dc2/src/pages/api/%5B...path%5D.ts#L31

What happens if we just stop doing that entirely in the API proxy?

**Comment by remipou** [comment]
got it, still calling `getfilters` that will throw an error if the filter is not valid but sending filter along with the other query parameters.

**Comment by remipou** [comment]
commented in the wrong place but I think this should be fixed as well: https://github.com/zetkin/app.zetkin.org/issues/2226#issuecomment-2393455178

**Review by richardolsson — APPROVED** [review]
This seems to be working as expected. I have tried the preview build, and reviewed the changes to the code and all looks good to me. Nice work!

**Pull request merged**
