### PR TITLE
Activity archives

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR adds archive pages to both the global scope and per-project. It also makes some other changes to reflect the conclusions reached in #1116.

### Global projects & activities overview
image

### Global archive
image

### Per-project archive
image

## Changes
* Adds archive pages both to the global scope (/organize/ID/projects/archive) and per project (/organize/ID/projects/ID/archive)
* Switches global activities list to show all activities, not just the unsorted/standalone ones
* Adds activities overview to the home screen of projects & activities (/organize/ID/projects)
* Fixes an issue in the call assignment, survey and task stores which caused items of these types to be reloaded on first use, even if they were just loaded collectively a second ago
* Fixes an issue in the `CallAssignmentListItem` which was rendering the wrong color for closed assignments
* Changes some strings to more correctly reflect the changes above

## Notes to reviewer
None

## Related issues
Undocumented. Supersedes #1116

### CODE REVIEW

**Comment by kaulfield23** [comment]
If I click the surveys in archives,activities, and overview it shows this error.
image

**Comment by kaulfield23** [comment]
When I click survey in overview activities and archives, it shows this error. I'm guessing it is because of loading?
image

**Comment by richardolsson** [comment]
> When I click survey in overview activities and archives, it shows this error. I'm guessing it is because of loading? I wonder if it is because of this weak wifi in cafe

Thanks for checking it out! This is because of a separate issue, that has actually been there a very long time and that I'm working on separately. See #1137

**Review by rebecarubio — APPROVED** [review]
I´ve tried it, looks more intuitive and nicer for the user!!! So cool everybody gave feedback and you´ve implemented it! 🚀

**Pull request merged**
