### PR TITLE
View cell for `local_person`

### LINKED ISSUE #910: View cell for Local Person column.
## Description
In a Local Person column, a user can add a local reference to a person - fx. this comes in handy when you want to note who is responsible for contacting a person.  User can pick a person, and their ID and basic information is retrieved as part of the view.

## Relevant Job Stories
- When I’m assembling a sheet of people to be reached out to, I want to be able to assign people to an organizer, so that several organizers can share the work of reaching out to them

## Requirements
- [x] Show avatar of person that is assigned
- [x] When editing show popper with search box and bigger avatar with button to unassign person
- [x] When searching, show first the people who are in the view, then all people matching search string

## Design specifications
https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=2358%3A48757&t=ZwOBKqXDfw3cdL7Y-4
bild

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR implements `local_person` view cells, which is the first type to include write support (i.e. changing the value of the cell). This means that the PR also includes some framework stuff to support this functionality, that can be reused by other cell types.

### Cells rendering avatars
image

### Popper for empty cell
Note the list of already assigned people (for easy access)
image

### Popper for assigned cell
image

### Popper while searching
Note the list of already assigned people being filtered as well.
image

### Popper in restricted (shared) mode
image

## Changes
* Adds new `ViewDataModel` and `ViewDataRepo` for retrieving view data, rows and columns
* Replaces `react-query` with new `ViewDataModel` in several places (but not everywhere yet, which has consequences – see notes to reviewer below)
* Adds context and a hook `useViewDataModel()` to make the model accessible to all view rendering components
* Adds context and a hook `useAccessLevel()` to make information about whether the view is being displayed in "restricted mode" (and with which access level) be available to all view rendering components
* Adds `LocalPersonColumnType`:
  * Renders simple strings for download
  * Renders avatar in cells where person is selected, or an empty icon avatar in empty cells
  * Shows popper on hover, as specified in issue
  * Popper only shows a read-only warning (and the selected person) if in restricted mode
* Changes `ZUIPersonSelect` to export `usePersonSelect` for reuse in other components (and uses it in this one)
* Fixes a bug in `usePersonSelect` so that the search field is reset after selecting a person
* Disables some tests that cannot pass right now (related to same issue as the one described in the notes to reviewer below)

## Notes to reviewer
This PR replaces how views get their rows and columns, now using the new `ViewDataModel` backed by the redux store. However, other places still use the old `react-query` way, meaning that the two cannot sync. This means that some actions that should trigger an update don't, forcing you to refresh before the update appears. This includes:

* Adding/removing a column
* Manually adding a person to a view
* Removing a person from a view
* Updating the Smart Search query for a view

## Related issues
Resolves #910

### CODE REVIEW

**Comment by ziggabyte** [comment]
First thing I notice when playing around, is that the cards end up outside of the screen. I have my screen normally set to 80%, and the first and second rows render like this. Third row and onward render the card above the cell, so no problem there, only the first two rows. 
bild
Becomes even more exagerated when I put my screen to 100% (which i think many people have their browsers on laptops at per default): 
bild
Is this something that can be updated to better calculate when the card will end up outside the screen? 
It is ofcourse possible to scroll into the card, so maybe that is good enough?

**Comment by ziggabyte** [comment]
Next thing I encounter that does not seem to work as intended, is that I can only re-assign to people in the "other people" seection, not from the "already in view" section. 
bild

Clicking Nora (or other name under Already in view header) does nothing
bild

Clicking Jane re-assigns to Jane (here Nora and all other names under Other people header works)
bild

**Comment by richardolsson** [comment]
> First thing I notice when playing around, is that the cards end up outside of the screen. I have my screen normally set to 80%, and the first and second rows render like this. Third row and onward render the card above the cell, so no problem there, only the first two rows. Is this something that can be updated to better calculate when the card will end up outside the screen? It is ofcourse possible to scroll into the card, so maybe that is good enough?

I guess I can put the popper to the side of the column, which might work?

image

>Next thing I encounter that does not seem to work as intended, is that when viewing the card for an assigned person, I can only re-assign to people in the "other people" seection, not from the "already in view" section.

At first I didn't understand this, but now I do and I can reproduce it. It's a bug. I will fix it!

**Review by ziggabyte — APPROVED** [review]
> I guess I can put the popper to the side of the column, which might work?

I don't know really? maybe it's fine to scroll into the card? It's maybe ok that it has this slight weirdness? I'm not sure I like the feel of it being to the side. I get unsure about everything now lol

I approve of this on the condition that the bug is fixed!

**Comment by richardolsson** [comment]
I have pushed my updates. Please have a look and see how you feel about the changes @ziggabyte.

**Review by ziggabyte — APPROVED** [review]
I think it works with the card to the side! And all the assigningn and unassigning is smooth for me :) So I give this the Ziggi Willpower Seal of Approval 🦭

**Pull request merged**
