### PR TITLE
Upgrade Next to version 14

### PR DESCRIPTION
**Pull request by henrycatalinismith**
This PR upgrades from Next v12 to Next ~v13~v14.  The general idea here is to take this a little bit slowly and break it up into very clearly differentiated steps. Ideally this PR will closely follow the [official v13 upgrade instructions](https://nextjs.org/docs/pages/building-your-application/upgrading/version-13) because nothing will go wrong that takes us outside that happy path.

To get this started, I'm just pushing a plain `package.json` & `yarn.lock` update because I think it'll be fun to surface any immediate build errors in public.

### CODE REVIEW

**Comment by henrycatalinismith** [comment]
So that very naive version bump commit gave the [following error](https://github.com/zetkin/app.zetkin.org/actions/runs/7240242655/job/19723004048?pr=1719).

$ cross-env NODE_ENV=production playwright test
Running 79 tests using [4](https://github.com/zetkin/app.zetkin.org/actions/runs/7240242655/job/19723004048?pr=1719#step:7:5) workers
TypeError: Cannot read properties of undefined (reading '0')
at nextBuild (/home/runner/work/app.zetkin.org/app.zetkin.org/node_modules/next/src/cli/next-build.ts:47:3[5](https://github.com/zetkin/app.zetkin.org/actions/runs/7240242655/job/19723004048?pr=1719#step:7:6))
at globalSetup (/home/runner/work/app.zetkin.org/app.zetkin.org/integrationTesting/globalSetup.ts:21:[11](https://github.com/zetkin/app.zetkin.org/actions/runs/7240242655/job/19723004048?pr=1719#step:7:12))
Error: TypeError: Cannot read properties of undefined (reading '0')

I asked Copilot what could be causing that, and it said:

> The error message "TypeError: Cannot read properties of undefined (reading '0')" typically means that you're trying to access an element of an array or object that doesn't exist. In this case, it seems like the nextBuild function is expecting an array as an argument, but it's not getting what it expects.
>
> In Next.js v13, the nextBuild function from next/dist/cli/next-build has been removed or changed, which is likely causing this issue.
>
> You should use the next build command directly in your CI/CD pipeline instead of importing it from next/dist/cli/next-build.

The code in [the follow-up commit](71c26f7a88f0b21f5d204b06df279f842be22e68) is more or less Copilot's suggestion except with its usual silly mistakes corrected. It seems to have progressed the build to the next error, so a successful first step.

**Comment by henrycatalinismith** [comment]
The next error's [`NextRouter was not mounted`](https://nextjs.org/docs/messages/next-router-not-mounted), which occurs like 100+ times during the unit tests. I've quickly tried replacing all the `useRouter` imports with [`next/compat/router`] but that's just returning `null` for the unit tests and so all the same tests are failing except with a different error message. Calling it a night there, good start!

**Comment by richardolsson** [comment]
The one remaining issue I can see now when looking around the pages is that there have been some sort of changes to links. The MUI links now render in blue, and errors are thrown in some places because the Nextjs `Link` component no longer likes to have `a` elements as children. So I will take on that work and fix it everywhere.

In the meantime @henrycatalinismith, maybe you can start playing with merging the work from this branch with the survey work, and begin moving the public survey page over to the app router?

**Comment by henrycatalinismith** [comment]
```
git checkout issue-1718/next-v13-upgrade
git rebase main
git push -f origin issue-1718/next-v13-upgrade
```

**Comment by henrycatalinismith** [comment]
Here's a sped-up screen recording showing a random series of interactions throughout the admin interface after running `rm -rf .next node_modules; yarn; yarn devserver` in this branch. Green build and nothing jumping out as obviously broken during exploratory testing, so it's over to you now @richardolsson! See what you think!

https://github.com/zetkin/app.zetkin.org/assets/566159/13b26163-f6aa-47c1-8a33-9ad2c05c3f50

**Comment by richardolsson** [comment]
Nice work! I will look more closely into this after we release some stuff that's in the pipeline.

**Review by richardolsson — COMMENTED** [review]
I've looked at this more closely and I think it looks fine. I'd like us to merge #1793 into this first though, so that we can get a preview live and have more people play around with it before we merge. Will request review there!

**Comment by richardolsson** [comment]
Public link for Vercel deployment: https://app-zetkin-org-git-issue-1718-next-v13-upgrade-zetkin.vercel.app?_vercel_share=G8GmbHFJC4sCBM5FLmEra96mb7ru08Kg

**Comment by ziggabyte** [comment]
Super nice to have the upgrade!! I have clicked around and did not experience anything strange, so it's a yes for me! :D

**Review by richardolsson — APPROVED** [review]
I have reviewed all the code, and also looked around the deployed preview, and I agree that it all looks good. Let's merge!

**Pull request merged**
