### PR TITLE
Undocumented/access mgmt refactor

### PR DESCRIPTION
**Pull request by kaulfield23**
## Description
This PR refactors `undocumented/access-management`

## Changes

* Adds `OfficialList.tsx`
* Changes variable,action names

## Related issues
Part of undocumented/access-management

### CODE REVIEW

**Review by rebecarubio — CHANGES_REQUESTED** [review]
Looks great! Amazing job renaming the actions too 💯 I just wondering if you can add the background color to follow the design in this PR? So then it's done!

**Comment by kaulfield23** [comment]
Oh yesss! on it!

**Comment by kaulfield23** [comment]
Looks like this now!

image

**Review by rebecarubio — APPROVED** [review]
Here we gooo 🚀

**Pull request merged**
