### PR TITLE
Rename "campaigns" to "projects"

### PR DESCRIPTION
**Pull request by richardolsson**
## Description
This PR replaces all user-facing occurrences of the word "Campaign" with the word "Project". It does not update internal identifiers in the code, because that risks making merging some other changes very difficult. We can do that later!

## Screenshots
image

## Changes
* Changes the default texts for all messages in the campaign feature `messageIds` module
* Renames the `src/pages/organize/[orgId]/campaigns` directory to `projects` and makes the necessary changes in all links everywhere

## Notes to reviewer
Note that I have willingly excluded changes internally in the code as they can be done whenever.

## Related issues
Solves part of #1097 (enough for R38, IMO)

### CODE REVIEW

**Comment by kaulfield23** [comment]
Okay! I think it is good to take step by step!  but will it be okay not to change path in integration tests?

**Comment by richardolsson** [comment]
> Okay! I think it is good to take step by step! but will it be okay not to change path in integration tests?

You're right! I forgot the playwright tests and have fixed them now. 😊

**Comment by richardolsson** [comment]
I believe everything is fixed and ready for review now!

**Review by kaulfield23 — APPROVED** [review]

**Comment by kaulfield23** [comment]
Nice! :)

**Comment by richardolsson** [comment]
> Nice! :) just one more question! will it cause much trouble if we change `[campId]` to `[projectId]` or something else?

Great question! I'm not sure how much work it would be. I have drawn the line between user-facing strings and internal strings, and I would say that `campId` is an internal string (it's the name of a variable/parameter). That's why I haven't spent any time on it at this point, because no user will ever see it, whereas labels in the interface and URLs are user-facing.

**Pull request merged**
