### PR TITLE
Issue 234/migrate to mui 5

### LINKED ISSUE #234: Migrate to MUI 5.0
https://next.material-ui.com/guides/migration-v4/

To implement after migration

- [ ] Moving tooltips on calendar bars and events
- [ ] Boxes should take refs without use of the spread operator
- [ ] Use the NextLinkComposed component?
- [ ] Nest themes in theme.js in a performant way, so that we can use the theme palette in style and prop overrides

### PR DESCRIPTION
**Pull request by nehahirve**
Resolves #234 

To do:

- [x] fix breaking tests

Date pickers inside the form elements work now, but they will not take the theme overrides without completing the next step:
- [ ] update `mui-rff` version and migrate `DatePickers` inside the forms (test this carefully)

The rest can be done after a merge, it's not breaking:
- [ ] Migrate away from JSS - https://mui.com/guides/migration-v4/#migrate-from-jss
- [ ] remove `@mui/styles` (this was used to keep JSS temporarily)
- [x] Uninstall old packages (`@material-ui/`)

### CODE REVIEW

**Comment by richardolsson** [comment]
Great work @nehahirve!

@djbusstop Any chance you could take a look at wrapping this up next?

**Comment by djbusstop** [comment]
@nehahirve @richardolsson taking a look at this now

**Comment by djbusstop** [comment]
The biggest, weirdest issue I'm having is when opening a modal it breaks a lot of the styles on the page re: font and padding...

**Comment by djbusstop** [comment]
Found visual bugs:
- Spacing between items on campaign cards grid
-

**Comment by djbusstop** [comment]
While working on this task, I have been stuck on updating the `mui-rff` and replacing the existing implementation of date-time pickers with `@mui/lab` and `mui-rff` versions. We did quite a bit of work on the intergration of these pickers with MUI + RFF. I think that it's possible that the libraries that we need to depend on are not ready to support our use case just yet. Making it all work together would require gluing together libraries that aren't ready to be integrated as well as the current implementation...

Here's the problems:
- `mui-rff` uses `@mui/lab` pickers, which would normally use a `LocalizationProvider` which would allow us to set the locale and date utils, however `mui-rff` doesn't allow us to use that provider and setting the locale for all components requires a workaround.
- The docs for `mui-rff` still say to use the previous `mui-pickers`, despite them not actually being what's used in `mui-rff`, that library uses the MUI lab pickers. So the docs don't explain how to successfully do the integration.
- The way the `mui-rff` pickers are implemented doesn't work with our current validation and error message implementation. Getting it to work will require a lot of 

I have been fighting against these issues for a while and came up with some  

Here's the long and short of it: the integration with `mui-rff` and dates is not yet ready to replace the mui pickers solution we had already implemented.

**Comment by djbusstop** [comment]
Closing as this work is on pause due to reasons described in above comment.

**Comment by richardolsson** [comment]
I did some research into React Final Form and mui-rff because I felt a little bit on the sidelines of this entire problem. Having watched a presentation on RFF and read the README of mui-rff, I'm not quite sure why we even need mui-rff. Couldn't we just use RFF directly and avoid the hassles above?

RFF seems like a very healthy open-source project, mui-rff less so. I accept that it may simplify some things a little bit, but I think it's also evident by the situation that we're in that it complicates other parts. And I feel like if we were to use RFF directly, we would at least own the complications ourselves, and not be dependent on a quite small library that is not very rapidly updated.

**Comment by richardolsson** [comment]
Actually, let's move the discussion to the still open issue #234.

**Pull request closed without merging**
