### PR TITLE
Issue 260/implement speed dial component

### LINKED ISSUE #260: implement speed dial on existing pages
- [x] `/orgs/[orgId]/campaigns`  > create campaign, create event
- [x] /orgs/[orgId]/campaigns/calendar  > create event
- [x] /orgs/[orgId]/campaigns/[campId]  > create event
- [x] /orgs/[orgId]/campaigns/[campId]/calendar  > create event

### PR DESCRIPTION
**Pull request by nehahirve**
resolves #260 
This PR implements the speed dial as follows:
- [x] `/organize/[orgId]/campaigns`  > create campaign, create event
- [x] /organize/[orgId]/campaigns/calendar  > create event
- [x] /organize/[orgId]/campaigns/[campId]  > create event
- [x] /organize/[orgId]/campaigns/[campId]/calendar  > create event

### CODE REVIEW

**Comment by richardolsson** [comment]
Is this ready for review @nehahirve?

**Comment by nehahirve** [comment]
@richardolsson Did I misunderstand, I thought I was waiting until both the finish events PR had been merged and the task form had been implemented, then merging main, and then finishing this up?

**Comment by richardolsson** [comment]
> @richardolsson Did I misunderstand, I thought I was waiting until both the finish events PR had been merged and the task form had been implemented, then merging main, and then finishing this up?

My impression was the opposite. I don't think you need to wait (unless I'm missing something).

The …/tasks and …/events paths don't exist, so those two items on your TODO list should not be necessary.

As for the other two, I think it's a good idea to let whoever creates the "Create task form" (@djbusstop?) also create the `SpeedDial` action for it.

**Comment by richardolsson** [comment]
There's a conflict. Can you merge `main` before I review @nehahirve?

**Review by richardolsson — APPROVED** [review]
Nice! Such a clean implementation. 🙌

**Pull request merged**
