### PR TITLE
prevent copied links to have same tag

### LINKED ISSUE #2075: Emails: Copying links also copy their tags (which should be unique)
## Description
Links (and buttons) in emails have "tags". They are not the same as the general concept of tags in Zetkin, and are not at all visible to users, but are more comparable to tags in analytics software. A link tag is basically an unique string that distinguishes that specific link from other links, even others with the same `href` URL. As such, it's important that tags are unique.

Tags are added to links and buttons when the link/button is created in the email editor. The tag string is stored on the HTML element in the Editor.js editor, and then serialized into to the Zetkin email content JSON format. But because of how Editor.js works, when some piece of content that includes links is copy-pasted, all data (including tags) are copied along with it.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects/1
2. Create an email
3. Go to the Compose tab
4. Write a paragraph
5. Select any word in the paragraph and turn it into a link to any URL
6. Copy the whole paragraph
7. Paste the paragraph
8. Look at the data of the email (in the browser dev tools network panel, redux dev tools or by browsing to `/api/orgs/1/emails/<EMAIL_ID>`)

### Expected Behaviour
The data should include two links, and the two links should have unique tags.

### Actual Behaviour
The data includes two links, but they both have the same tag.

## Screenshots (if you have any)
None

## Proposed solution
One idea would be to not generate a random tag when the link is created (which requires it to be stored somewhere) but instead as part of the serialization (in `editorjsBlocksToZetkinBlocks()`). The tags do not need to be stable, i.e. they can be constantly updated until the email is scheduled, after which they cannot change (but neither can any other part of the content).

### PR DESCRIPTION
**Pull request by remipou**
## Description
This PR prevents a copied/pasted link to have same "tag"

## Changes
The tag is now generated later in the serialization process.

## Related issues
Resolves #2075 (https://github.com/zetkin/app.zetkin.org/issues/2075)

### CODE REVIEW

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work @remipou! I'm hugely impressed by the number (and complexity) of issues that you've been able to take on in such a short time.

I do have three things that I would like you to address with this PR before I feel it can be merged.

## Unstable tag
First, I'm super impressed with the simplicity this solution. There is one drawback though, and I want to run it by you to see what you think. Maybe it's just a philosophical problem. Before, a link would get it's tag when it was created, and that tag would then stay stable. But right now, every time you edit the email, it's serialized again and that serialization creates a new tag. You can try it by adding a link anywhere, and then just editing any part of the email while watching the network panel (a `PATCH` will be made when you stop editing for a second or so).

Again, I'm not sure if there are really any practical implications of this, because the tag is only really relevant internally and only, strictly speaking, _needs_ to be stable once the email is sent (after which editing is prohibited anyway). But it still kinda rubs me the wrong way, if you catch my drift. 😊 

## Unit tests fail
As you may have seen, there are unit tests failing because you've made changes to htmlToInlineNodes() without tending to the tests in some way. Depending on how you solve (or choose not to solve) my "Unstable tag" concern above, the tests may or may not need to be updated.

## Issue remains for buttons
This same issues also exists for buttons. It was only briefly mentioned in the original issue so I completely understand that you missed it. But maybe you can try to fix that at the same time?

**Comment by remipou** [comment]
Funny that you mentioned it, I was a bit concern about it too, I'll give it another try and fix the buttons and the tests.

**Comment by remipou** [comment]
@richardolsson I think the stability of the tags is solved now. The solution for the buttons was not as straight forward, tell me what you think about it.

**Comment by richardolsson** [comment]
The tags are not stable in my testing. Lets take a closer look at this together (after the Code Camp)!

**Comment by remipou** [comment]
working on a solution

**Comment by ziggabyte** [comment]
Hi @remipou ! I see that you made a comment a while back that you were working on a solution for the comments you got on this. Just wanted to check in and see if you wanna keep working on this, or if you would feel ok if someone from the day-to-day team did the finishing touches to bring it across the finish line? :D

**Comment by remipou** [comment]
@ziggabyte I'm sorry I didn't manage to fix it. I had a new try, trying to use editorjs paste event (https://editorjs.io/paste-substitutions/) but it wasn't successful.

**Comment by ziggabyte** [comment]
> @ziggabyte I'm sorry I didn't manage to fix it. I had a new try, trying to use editorjs paste event (https://editorjs.io/paste-substitutions/) but it wasn't successful.

Absolutely no problem, the editor is not very friendly to work with in a lot of ways and we are looking into building our own wysiwyg editor that can better handle these things, but your effort to solve this is greatly appreciated, and someone might jump in if they are in the mood and attempt to continue on it!

**Comment by richardolsson** [comment]
Lets close this and aim to fix it in a new editor instead.

I think you made a good attempt @remipou, and there is no shame in being defeated by Editor.js. We all have, multiple times, and that's why we plan to replace it. 😊

**Pull request closed without merging**
