### PR TITLE
Change title of activities tab in All projects to Uncategorised activities

### PR DESCRIPTION
**Pull request by niklasva82**
## Description
This PR changes the title of the activities tab in All projects to "Uncategorised activities"

## Screenshots
bild

## Changes
* Changes title of activities tab in `projects/activities`

## Notes to reviewer
[Add instructions for testing]

## Related issues
Part of #1067

### CODE REVIEW

**Comment by richardolsson** [comment]
I'm not sure what I think about this. The change itself is fine, but I'm wondering if it's the right solution to the problem. Should the "All projects" section not include all activities, regardless of project?

Maybe we should have a special (meta/fake) project called "Unsorted" where unsorted activities (and the archive for unsorted activities) are found?

Curious to hear what others think about this!

**Comment by niklasva82** [comment]
It does make sense that the All projects tab contains all the activites. And then you mean the uncategorised activities would go into the "fake" project?

**Comment by richardolsson** [comment]
> It does make sense that the All projects tab contains all the activities. And then you mean the uncategorised activities would go into the "fake" project?

Yes, exactly! But I haven't thought this through entirely.

**Comment by niklasva82** [comment]
Would the All projects activity tab contain *all* projects, or just the ones that haven't been archived?

**Comment by richardolsson** [comment]
> Would the All projects activity tab contain _all_ projects, or just the ones that haven't been archived?

IMO, under "All projects" (/organize/1/projects) the "Overview" tab should contain the currently **active** projects, and the "Activities" tab (/organize/1/projects/activities) should include **upcoming** activities _regardless of project_.

A project overview (/organize/1/projects/2) should show active activities this week, and it's activities tab (/organize/1/projects/2/activities) should show all **upcoming** activities.

Finally, a separate "unsorted" project (e.g. /organize/1/projects/unsorted) should contain active activities this week that _do not_ belong to a project. And I guess it would have an "activities" tab as well.

> And should there in the second case also be an Archived tab for for All projects?

Yes, there would need to be an archive tab in each of the three sections described above.

But again, this needs to be thought through properly and maybe get some input from @yusf and @Bagera.

**Comment by niklasva82** [comment]
Alright this all makes sense. I will make some preparations for something along these lines and hold off for input from @yusf and @Bagera.

> IMO, under "All projects" (/organize/1/projects) the "Overview" tab should contain the currently active projects, and the "Activities" tab (/organize/1/projects/activities) should include upcoming activities regardless of project.
Where do archived projects go? Is there a design for this?

**Comment by niklasva82** [comment]
This is the current state. The All projects Activity tab now shows all active activities, and the Archive tab on both All projects and the current projects shows all archived activities.
bild

**Comment by richardolsson** [comment]
After working with @yusf and @Bagera we now have a decision on how this should be structured. Diagram below:

image

In summary:

* "Root" section has the following tabs:
  * "Overview", which lists projects (current and old) and an overview of most relevant activities regardless of project
  * "Activities", which lists all current/upcoming activities, regardless of project
  * "Archive", which lists old activities (not projects, which are on the overview!)
* A "Project" section has the following tabs:
  * "Overview" which shows an overview of the most relevant activities in that project
  * "Activities", which lists all current/upcoming activities in that project
  * "Archive", which lists old activities in that project
* There is no "Unsorted" pseudo-project

**Comment by richardolsson** [comment]
Superseded by #1138

**Pull request closed without merging**
